### ISSUE TITLE
[BUG] Adding Power and Custom Power commands won't save

### ISSUE THREAD

**Issue by MTrab** [NotExpectedYet/OctoFarm#234]
### To better help the developer understand your issue, please fill in the information below. Failing to do so will waste the developer and your own time in sorting the issue. Thanks!

**Describe the bug**
When entering information in Power and Custom Power Commands fields, nothing is saved.
After pressing save and reloading the page, the fields are back to default text again.

**To Reproduce**
1. Go to 'Printer Settings'
2. Click on 'Power'
3. Add information in the fields
4. Press Save
5. Reload the page
6. Observe the fields are back to default

**Expected behavior**
Settings should be saved

**Screenshots**
Before Save/Reload:
![image](https://user-images.githubusercontent.com/14296463/105607313-50fe6f80-5d9e-11eb-9788-13625bd997d8.png)

After Save/Reload:
![image](https://user-images.githubusercontent.com/14296463/105607347-6c697a80-5d9e-11eb-86de-f1d2f0a91451.png)

**Versions (please complete the following information):**
 - NodeJS Version [e.g. 13] (??)
 - OctoFarm Version [e.g. 1.5.5.7] 1.1.6 (Octofarm-Monolithic)
 - OctoPrint Version [e.g. 1.4.1]  1.5.3
 - OctoPrint Plugins [e.g. bed visualiser, octoklipper, printtimegenius] Enclosure Plugin

**Additional context**
N/A

**Comment by NotExpectedYet** [comment]
Hello, could you update to 1.1.7 please and see if that rectifies the issue? 

I'll do some testing here in a minute see if I can reproduce.

**Comment by NotExpectedYet** [comment]
Confirmed. Don't worry about updating. Will add it to the 1.1.8 release.

**Comment by NotExpectedYet** [comment]
For a work around, save the settings and then press the re-sync button for the printer. It will grab them back from OctoPrint.

**Comment by MTrab** [comment]
Updated to 1.1.8, and settings still not being saved. Issue still persists.

**Comment by NotExpectedYet** [comment]
Yep just confirmed. What the hell was I smoking yesterday. I'll have another look through week, that's annoying I confirmed it saving yesterday grr.

**Comment by NotExpectedYet** [comment]
Right certainly fixed this time. It was the OctoPrint update causing issues... The thing was sending null values back to it, rather than the saved ones then re-syncing itself and clearing. This might explain some other issues I've seen with people not having saved settings. Fixed for it clearing out settings/appearance too. Thanks for reporting, wouldn't have seen that at all otherwise.

**Comment by NotExpectedYet** [comment]
It's on the master branch, I'll back fill development shortly.

**Comment by MTrab** [comment]
Nice - looking forward test it when pushed into monolithic.

**Comment by NotExpectedYet** [comment]
Just finished some tweaks to the new graphs too and pushed to both master and dev. 

Monolithic image on docker hub shouldn't be too long.

**Comment by NotExpectedYet** [comment]
I believe it's live :)

**Comment by MTrab** [comment]
Hmmm - the image did update, but still reads 1.1.8.

Unfortunately still not saving :(

**Comment by NotExpectedYet** [comment]
I haven't formalised it as a version yet so will still read that. Grr, this one is been annoying. It's certainly saving on my end. Just tried it with saving blank (no edits to modal), and saving 1 line and leaving the others. 

All the monolithic builds have been complete, could you just confirm there isn't another?

**Comment by MTrab** [comment]
Nope - no new images now

**Comment by NotExpectedYet** [comment]
I've just forced a push through for the development version. 

Would you mind switching over and seeing if that works? I've updated the version to 1.1.9-dev1 so you can see the change. 

It sounds like the image isn't pulling the new one, but it should be so just rather confirm.

**Comment by NotExpectedYet** [comment]
10.20 GMT was the last monolightic build I believe so might have just taken some time to go through.

**Comment by MTrab** [comment]
Switched to octofarm/octofarm:monolithic-dev, but version still reads 1.1.8 :/

**Comment by MTrab** [comment]
And still not saving

**Comment by NotExpectedYet** [comment]
It's still building for the 1.1.9-dev1 shouldn't be too long

**Comment by NotExpectedYet** [comment]
I can't reproduce at the moment with your original steps. Not sure what's going on at the moment.  

Could you also send through the octofarm-API logs as well please?

**Comment by MTrab** [comment]
Custom power on command:
`[PrinterURL]/plugin/enclosure/setIO?status=true&index_id=1&apikey=[PrinterAPI]`

Custom power off command:
`[PrinterURL]/plugin/enclosure/setIO?status=false&index_id=1&apikey=[PrinterAPI]`

Just in case you'd want to try for your selv with the exact strings I use.

**Comment by MTrab** [comment]
[OctoFarm-API.log](https://github.com/NotExpectedYet/OctoFarm/files/5865983/OctoFarm-API.log)

**Comment by NotExpectedYet** [comment]
I was checking the restart commands... 

I'll take a look at those in a bit sorry, didn't realise it was those as well.

**Comment by NotExpectedYet** [comment]
Can you confirm the restart commands are staying now please?

**Comment by MTrab** [comment]
The restart commands doesn't save either, so just as well ... ;)

**Comment by NotExpectedYet** [comment]
How are you updating the container? as I can't reproduce with the restart commands. 

Just the custom power commands currently. 

Monolithic has certainly built. You should see 1.1.9-dev1 when you update this time.

**Comment by MTrab** [comment]
Using a custom update script: https://pastebin.com/yCWe0dUq

Will try an update again

**Comment by NotExpectedYet** [comment]
> Using a custom update script: https://pastebin.com/yCWe0dUq
> 
> Will try an update again

No that's perfect, just wanted to confirm that it was updating properly but that should. Some people just restart the container aha. 

I'll check the custom power commands shortly, just let me know if restart still isn't persisting and I'll have a look at that as well.

**Comment by NotExpectedYet** [comment]
10:42 that built so should certainly have a new pull. 

Just confused as hell why the restart ain't saving for you aha. Be my goof somewhere.

**Comment by MTrab** [comment]
Okay - not it reads 1.1.9-dev1.
Still not saving restart commands thou :/

**Comment by NotExpectedYet** [comment]
Grrr. Can't understand that at all. Sorry for the mess around. 

I'll do some tests in a bit see if I can't figure it out.

**Comment by MTrab** [comment]
Let me know if you need anything

**Comment by NotExpectedYet** [comment]
Some time would be nice aha. 

Be about mid-week I think I'll be able to check as I've got to go back into my day job tomorrow.

**Comment by MTrab** [comment]
It's okay.
I've been doing some testing on 1.1.9-dev1 - and it looks like the restart commands get saved afterall, it just returns N/A in the text fields afterwards.
The restart command button becomes visible and works after a resync.

**Comment by MTrab** [comment]
![image](https://user-images.githubusercontent.com/14296463/105729888-f8f67300-5f2d-11eb-9c72-6c9bfc5fc57b.png)
![image](https://user-images.githubusercontent.com/14296463/105729929-04499e80-5f2e-11eb-9d15-897730bf560a.png)

**Comment by NotExpectedYet** [comment]
> It's okay.
> I've been doing some testing on 1.1.9-dev1 - and it looks like the restart commands get saved afterall, it just returns N/A in the text fields afterwards.
> The restart command button becomes visible and works after a resync.

Hmmm that's still weird because on mine it pulls back through... confusing! I wonder if it's something to do with me having long standing data but I tried with a fresh printer setup. 

Aye that makes sense as the push to OctoPrint was working and a re-sync just collects the commands from there and keeps them in memory. Before I was updating OctoPrint with blank values which is why it previously went in circles. I've probably missed something again.

At least those are working. 

The power commands below "might" work the same. The only difference there is they go back to my database rather than updating octoprint. I would make sure all are filled in though.

**Comment by MTrab** [comment]
Just tried with the custom commands, those doesn't work still. Will be awaiting what you find :)

**Comment by NotExpectedYet** [comment]
Thanks for the confirmation. 

Hopefully I should get some time tomorrow to have a look into it. It's my fault I should have paid more attention this morning so sorry about that.

**Comment by MTrab** [comment]
No worry . just happy you'll take the time to look into this :)

**Comment by NotExpectedYet** [comment]
Oh OctoFarm is my baby I don't like bugs 😅. I certainly will though.

**Comment by NotExpectedYet** [comment]
Yo, just pushed another attempted fix to development if you get chance to try. 

I tested here and all was working fine and updating straight away after a refresh. Fingers crossed same on your end. Will be -dev2

**Comment by MTrab** [comment]
Hmmm - Save button seems to not be working in -dev2.
Nothing happens when pressing Save.

**Comment by NotExpectedYet** [comment]
Could you send the API log through please?

**Comment by MTrab** [comment]
[OctoFarm-API (1).log](https://github.com/NotExpectedYet/OctoFarm/files/5871577/OctoFarm-API.1.log)

**Comment by NotExpectedYet** [comment]
Hmm its certainly sending the information and receiving it. 

I'll take another look at the code in a bit and see if I missed something.

**Comment by NotExpectedYet** [comment]
Does anything come up in the browser console window when you press save?

**Comment by MTrab** [comment]
No, nothing comes up. And the commands seems not to be saved either.

**Comment by NotExpectedYet** [comment]
Press F12 on your browser and click the console tab. 

Then press save, it will show errors if there are any.

**Comment by MTrab** [comment]
Nothing happens in the console

**Comment by MTrab** [comment]
When pressin save WITHOUT entering anything, the save button works

**Comment by NotExpectedYet** [comment]
What nodejs version are you running?

**Comment by MTrab** [comment]
Using 12.16.3-0017

**Comment by NotExpectedYet** [comment]
Not that then hmmm

**Comment by NotExpectedYet** [comment]
Hello, I have made some tweaks and pushed a new version to development. Will be -dev3. Would you mind testing? 

If it fails again this time I have bolstered the State log to show what's actually going on. Should at least either fix it or allude me to what is happening.

**Comment by MTrab** [comment]
Still no luck :(
[OctoFarm-API (2).log](https://github.com/NotExpectedYet/OctoFarm/files/5886588/OctoFarm-API.2.log)
[OctoFarm-State.log](https://github.com/NotExpectedYet/OctoFarm/files/5886596/OctoFarm-State.log)

**Comment by NotExpectedYet** [comment]
Your log provided only goes up to 25th of January, need the attempts today please

**Comment by MTrab** [comment]
Strange - tried right after upgrade of the container.
I'll give it another try.

**Comment by NotExpectedYet** [comment]
You need a OctoFarm-State#.log that file without the number is the oldest.

**Comment by MTrab** [comment]
Remember - my save button doesn't seem to work when I have anything entered in the boxes.
[OctoFarm-State1.log](https://github.com/NotExpectedYet/OctoFarm/files/5886659/OctoFarm-State1.log)

**Comment by NotExpectedYet** [comment]
Aye I know there we're no errors in the browser so that would be the server not responding correctly to the request. 

{
  "state": "Disconnected",
  "printer": {
    "printerName": "",
    "printerURL": "",
    "index": "60096307de188800262631e0",
    "cameraURL": "",
    "apikey": ""
  },
  "connection": {
    "preferredPort": "0",
    "preferredBaud": "115200",
    "preferredProfile": "_default"
  },
  "systemCommands": {
    "serverRestart": "sudo service octoprint restart",
    "systemRestart": "sudo shutdown -r now",
    "systemShutdown": "sudo shutdown -h now"
  },
  "powerCommands": {
    "powerOnCommand": "",
    "powerOnURL": "[PrinterURL]/plugin/enclosure/setIO?status=true&index_id=1&apikey=[PrinterAPI]",
    "powerOffCommand": "",
    "powerOffURL": "[PrinterURL]/plugin/enclosure/setIO?status=false&index_id=1&apikey=[PrinterAPI]",
    "powerToggleCommand": "",
    "powerToggleURL": "",
    "powerStatusCommand": "",
    "powerStatusURL": "",
    "wol": {
      "enabled": false,
      "ip": "",
      "port": "",
      "interval": "",
      "count": "",
      "MAC": ""
    }
  },
  "costSettings": {
    "powerConsumption": null,
    "electricityCosts": null,
    "purchasePrice": null,
    "estimateLifespan": null,
    "maintenanceCosts": null
  },
  "profileID": "_default",
  "profile": {
    "name": null,
    "color": "default",
    "model": null,
    "volume": {
      "formFactor": "rectangular",
      "width": null,
      "depth": null,
      "height": null
    },
    "heatedBed": true,
    "heatedChamber": false,
    "axes": {
      "x": {
        "speed": null,
        "inverted": false
      },
      "y": {
        "speed": null,
        "inverted": false
      },
      "z": {
        "speed": null,
        "inverted": false
      },
      "e": {
        "speed": null,
        "inverted": false
      }
    },
    "extruder": {
      "count": null,
      "nozzleDiameter": null,
      "sharedNozzle": false
    }
  },
  "gcode": {
    "afterPrintCancelled": "",
    "afterPrintDone": "",
    "afterPrintPaused": "",
    "afterPrinterConnected": "",
    "afterToolChange": "",
    "beforePrintResumed": "",
    "beforePrintStarted": "",
    "beforePrinterDisconnected": "",
    "beforeToolChange": ""
  },
  "other": {
    "enableCamera": true,
    "rotateCamera": false,
    "flipHCamera": false,
    "flipVCamera": false,
    "enableTimeLapse": true,
    "heatingVariation": "",
    "coolDown": ""
  }
}

I can see the request been sent to the server. 

But there is nothing in the state log with my new logging. Nothing at all. That seems to me like that hasn't updated, your certainly on -dev3?

![image](https://user-images.githubusercontent.com/61137988/106131611-d006f580-615a-11eb-9ad6-ef3f67a09b4e.png)


`Thu, 28 Jan 2021 10:50:52 GMT | INFO | OctoFarm-State.log | Grabbed 2 for checking | `

That was the last reboot of OctoFarm for your server and is before the monolithic image actually pushed so as far as I can tell by the logs you haven't updated anything.

![image](https://user-images.githubusercontent.com/61137988/106131694-ead96a00-615a-11eb-868a-7bc68bd50f73.png)

**Comment by MTrab** [comment]
![image](https://user-images.githubusercontent.com/14296463/106131887-853dab80-6163-11eb-8a8a-98fbe728358d.png)
I'll try updating again, perhaps something missed?!

**Comment by NotExpectedYet** [comment]
Worth a try. 

It seems nodejs is giving me a run for my money this week.

**Comment by MTrab** [comment]
Some parts updated again. New log.
[OctoFarm-State1 (1).log](https://github.com/NotExpectedYet/OctoFarm/files/5886720/OctoFarm-State1.1.log)

**Comment by NotExpectedYet** [comment]
Success! Let me read through these :D

**Comment by NotExpectedYet** [comment]
Right that function is literally getting stuck for you and I'm not sure why. 

I wonder if it's a by-product of the issue, which it shouldn't be because a new value should just overwrite the original values. 

I've got your attempting to save log, but it goes no further. 

I'm just pushing some improved logging to find out what it's having issues with. 

If you wanted to test a theory I have. Could you delete the printer and re-add it afresh? I'm wondering if there's a snafu in the database from our earlier attempts. Although there shouldn't be, I'm just confused why I can't reproduce this at the minute so something is out of sync in OctoFarm.

**Comment by NotExpectedYet** [comment]
Is your octoprint instance online whilst trying to do this btw?

**Comment by MTrab** [comment]
Yes Octoprint is online, only the printer is disconnected.

**Comment by NotExpectedYet** [comment]
Ahh cool cheers, was just to rule something out. I'm just about to push another set of loggin imrovements and you should see an error at least this time in the UI. Be dev4, I'll let you know when it's built.

**Comment by NotExpectedYet** [comment]
![image](https://user-images.githubusercontent.com/61137988/106134934-25450600-615f-11eb-8179-07cfd750540d.png)


I've just pushed. 

You'll now see the above in the console too. Will hopefully help me track down what's going on here. 

You shouldn't have to enter the restart commands everytime btw, it looks like you are so if not just disregard aha. 

be about 10-15 but I'll reply here when I notice it's built on docker hub

**Comment by NotExpectedYet** [comment]
Monolithic has built

**Comment by MTrab** [comment]
New logfile - and yes, JSON object visible in console
[OctoFarm-State1 (2).log](https://github.com/NotExpectedYet/OctoFarm/files/5887107/OctoFarm-State1.2.log)

**Comment by NotExpectedYet** [comment]
> New logfile - and yes, JSON object visible in console
> [OctoFarm-State1 (2).log](https://github.com/NotExpectedYet/OctoFarm/files/5887107/OctoFarm-State1.2.log)

Well my "improved" logging produced this...` HEY THE ERROR WERE LOOKING FOR! | data:{} | `

Did you try deleting the printer and adding it again? As long as it's got the same name History and that will still be connected.

**Comment by NotExpectedYet** [comment]
Do you have the pm2.error.log file? Might have the full message in there

**Comment by NotExpectedYet** [comment]
I've also just done dev4 to improve the loggin, hopefully will print out the error now.

**Comment by MTrab** [comment]
Yes, tried deleting and adding again, same name and API key. Still no luck.
Updated to dev4, still no luck and still no reaction when pressing the Save button

[Logs.zip](https://github.com/NotExpectedYet/OctoFarm/files/5888231/Logs.zip)

**Comment by NotExpectedYet** [comment]
I believe I've fixed it. Just confirming.

**Comment by MTrab** [comment]
Nice - just say when an update are ready

**Comment by NotExpectedYet** [comment]
Confirmed! 

New Printer added -> setup power settings, and also correctly pulled from OctoPrint originally. 

Then move on to setup the power settings with just a URL and ignoring the "Command" block, updated fine with each singly, and multiple. 

It's building so should be about 15 mins but will confirm.

**Comment by MTrab** [comment]
Hmmmmm - settings are read, but something is off when saving custom commands:
![image](https://user-images.githubusercontent.com/14296463/106264922-9996ac80-6226-11eb-9b44-7c0e75f70e14.png)

**Comment by MTrab** [comment]
`Fri, 29 Jan 2021 10:38:42 GMT | INFO | OctoFarm-State.log | Attempting to save:  | data:{"state":"Disconnected","printer":{"printerName":"","printerURL":"","index":"6012a1b726f97000191982af","cameraURL":"","apikey":""},"connection":{"preferredPort":"","preferredBaud":"115200","preferredProfile":"_default"},"systemCommands":{"serverRestart":"","systemRestart":"","systemShutdown":""},"powerCommands":{"powerOnCommand":"","powerOnURL":"[PrinterURL]/plugin/enclosure/setIO?status=true&index_id=1&apikey=[PrinterAPI]","powerOffCommand":"","powerOffURL":"","powerToggleCommand":"","powerToggleURL":"","powerStatusCommand":"","powerStatusURL":"","wol":{"enabled":false,"ip":"","port":"","interval":"","count":"","MAC":""}},"costSettings":{"powerConsumption":null,"electricityCosts":null,"purchasePrice":null,"estimateLifespan":null,"maintenanceCosts":null},"profileID":"_default","profile":{"name":null,"color":"default","model":null,"volume":{"formFactor":"rectangular","width":null,"depth":null,"height":null},"heatedBed":true,"heatedChamber":false,"axes":{"x":{"speed":null,"inverted":false},"y":{"speed":null,"inverted":false},"z":{"speed":null,"inverted":false},"e":{"speed":null,"inverted":false}},"extruder":{"count":null,"nozzleDiameter":null,"sharedNozzle":false}},"gcode":{"afterPrintCancelled":"","afterPrintDone":"","afterPrintPaused":"","afterPrinterConnected":"","afterToolChange":"","beforePrintResumed":"","beforePrintStarted":"","beforePrinterDisconnected":"","beforeToolChange":""},"other":{"enableCamera":true,"rotateCamera":false,"flipHCamera":false,"flipVCamera":false,"enableTimeLapse":true,"heatingVariation":"","coolDown":""}} | 
Fri, 29 Jan 2021 10:38:42 GMT | ERROR | OctoFarm-State.log | ERROR updating printer  | data:"\"Cannot read property 'powerOnURL' of null\"" | 
`

From the state log

**Comment by NotExpectedYet** [comment]
It's still building the -dev5 man, but that's just to remove the profile failed to update error your seeing. Basically those power commands don't get pushed back to OctoFarm but the others do. I cleaned up those errors.

**Comment by MTrab** [comment]
Oh okay, I'll try again later then :)

**Comment by NotExpectedYet** [comment]
It will literally just stop showing those two red alerts. The commands should be working and you should see it on the power dropdown on a refresh?

**Comment by NotExpectedYet** [comment]
hmmm hang on somethings still going on.

**Comment by NotExpectedYet** [comment]
That should be working now for the saving and stuff. 

I'm just pushing a fix for the power status grabbing without existing but doesn't effect anything just extra calls that don't go anywhere. 

Man.. that was an annoying one! proper did myself over aha.

**Comment by NotExpectedYet** [comment]
Just to mention will be on development until I fix the graph issue with long standing databases.

**Comment by MTrab** [comment]
Indeed it's saved now, but doesn't seem like it's actually firing the action when selected.
What log could I look for clues in?

**Comment by NotExpectedYet** [comment]
It's all client side so the console in the browser. 

I'll see if I can reproduce with your url above

**Comment by NotExpectedYet** [comment]
Yeah fires for me fine

**Comment by NotExpectedYet** [comment]
![Screenshot_20210129_170702](https://user-images.githubusercontent.com/61137988/106305611-ce215d00-6254-11eb-9091-a8faff70769f.png)

**Comment by NotExpectedYet** [comment]
Your command won't work though with the current code. Your firing a custom command to OctoPrint not a custom url. I don't specifically send the API key with the command. If you get a CORS policy above, let me know I'll tweak it for you. I checked the current power command plugins and my method supported all those, didn't realise enclosure plugin had that option too.

**Comment by NotExpectedYet** [comment]
Going to depend how that plugin utilises OctoPrints api I would have thought.

**Comment by MTrab** [comment]
![image](https://user-images.githubusercontent.com/14296463/106306244-0f6a3a80-625e-11eb-9ec0-476c50c3e9fd.png)

Yup - CORS error

**Comment by NotExpectedYet** [comment]
His documentation is mis-leading for his API. You'd still have to send the X-Api-Key header with the requests he's detailed on his Wiki. 

I've just pushed the fix for you, will let you know when it's built again :)

**Comment by NotExpectedYet** [comment]
It's built, sorry that got auto closed when I merged with master. Please open if your still getting a CORS error :)

**Comment by MTrab** [comment]
Still getting the CORS errors

**Comment by NotExpectedYet** [comment]
Can you show me the console output please?

**Comment by MTrab** [comment]
![image](https://user-images.githubusercontent.com/14296463/106356088-20b65400-62fd-11eb-8b66-6693e27de4ee.png)

When copying the URL to a new pane in the browser, it works as expected.

**Comment by NotExpectedYet** [comment]
I'll have to setup the plugin and run some tests for it not sure. All I'm making is a get requests the same as the browser would, so with or without the api key should technically work.

**Comment by MTrab** [comment]
Still CORS problems, even on the recent release

![image](https://user-images.githubusercontent.com/14296463/107759044-08e0c600-6d28-11eb-83af-68d05f826e7c.png)

**Comment by NotExpectedYet** [comment]
Don't get it at minute, and I can't install enclosure plugin to test it because it keeps coming back "unknown".

**Comment by NotExpectedYet** [comment]
Ahhh your still making a post request not a get request... could you check the latest push please on dev? will say 1.1.11-dev9. 

The flag to not use the json data in command is been missed. I put some console logs in for that, if it doesn't work again could you send those please?

**Comment by NotExpectedYet** [comment]
I've just fixed the feed rate too, I updated that twice now dunno how that dissapeared.

**Comment by MTrab** [comment]
> Ahhh your still making a post request not a get request... could you check the latest push please on dev? will say 1.1.11-dev9.
> 
> The flag to not use the json data in command is been missed. I put some console logs in for that, if it doesn't work again could you send those please?

Still no luck

![image](https://user-images.githubusercontent.com/14296463/107762886-f9fd1200-6d2d-11eb-8159-0f892b823159.png)

**Comment by NotExpectedYet** [comment]
It's that current_value variable let me have a look where that's coming from... It's still skipping the get request and making a post because of that.

**Comment by MTrab** [comment]
Okay 1.1.11-dev9 is VERY fu-bar :( Nothing works.
Can't even open a printers control panel.

![image](https://user-images.githubusercontent.com/14296463/107763127-62e48a00-6d2e-11eb-92e3-28770c6617df.png)

Missing states on the list
![image](https://user-images.githubusercontent.com/14296463/107763186-7b54a480-6d2e-11eb-982f-8af1b9e72d90.png)

**Comment by MTrab** [comment]
> It's that current_value variable let me have a look where that's coming from... It's still skipping the get request and making a post because of that.

current_value is the JSON property  in the enclosure plugins response which contains the current state (true/false), so that's one I have defined.

**Comment by MTrab** [comment]
![image](https://user-images.githubusercontent.com/14296463/107763399-e1412c00-6d2e-11eb-8dba-ccf9f34dcae8.png)

**Comment by NotExpectedYet** [comment]
To use your plugin correctly all your custom power commands should have nothing in the settings like this:
![image](https://user-images.githubusercontent.com/61137988/107763435-899ec280-6d26-11eb-8dae-7ad6217c9890.png)

**Comment by NotExpectedYet** [comment]
Your current_value variable is been sent with the command to power on/off by the looks and it shouldn't be

**Comment by MTrab** [comment]
It's only the state line that have the current_value defined.
Haven't tested the on/off commands yet, as both printers are currently printing.

**Comment by NotExpectedYet** [comment]
> It's only the state line that have the current_value defined.
> Haven't tested the on/off commands yet, as both printers are currently printing.

It won't work with that in, and that's gonna keep failing as I poll for the status.

**Comment by NotExpectedYet** [comment]
The first field is for sending data not receiving. 

![image](https://user-images.githubusercontent.com/61137988/107764084-80fabc00-6d27-11eb-978f-f6a7bb10a0ad.png)
Should all be like this, just with the correct URLs as I copied and pasted the first one I saw you use to test.

**Comment by MTrab** [comment]
Right now I can't change it - need to downgrade as the latest release have crashed everything.

**Comment by NotExpectedYet** [comment]
> Right now I can't change it - need to downgrade as the latest release have crashed everything.

I've no idea what's going on there because I can't reproduce it. It looks like something is failing to scan with your printer as there is no settings been grabbed.

**Comment by NotExpectedYet** [comment]
You send me some recent state logs through to see what I've goofed?

**Comment by NotExpectedYet** [comment]
Seems there's a bug blanking the field anyway -_-

**Comment by MTrab** [comment]
Restart of the docker seemed to fix all of the missing data. But can't remove the current_value setting.
When deleting the text and saving, it's still there in the view - even after another restart of the docker, and still in the field as well.

**Comment by NotExpectedYet** [comment]
> Restart of the docker seemed to fix all of the missing data. But can't remove the current_value setting.
> When deleting the text and saving, it's still there in the view - even after another restart of the docker, and still in the field as well.

Aye it seems I'm not letting the fields blank out. Just discovered it now when I thought best test to see if that's possible. Well least the other thing isn't a major goof. I'll just sort the settings.

**Comment by NotExpectedYet** [comment]
Right so I'm a bit stuck with that with the current logic. I send blank fields to indicate a change so might take me some time to get that sorted. For now, your best bet will be MongoDB Compass to just blank that field out in your printers power settings. Sorry about that, that settings section has been a royal pia and I wanna nuke it but I don't have time so I'll try and get it patched.

**Comment by NotExpectedYet** [comment]
#276 to track this properly.

**Comment by MTrab** [comment]
On/Off commands working properly now. Status not, but that might be down to that JSON object returned from enclosure plugin.

**Comment by NotExpectedYet** [comment]
> On/Off commands working properly now. Status not, but that might be down to that JSON object returned from enclosure plugin.

Sounds like it certainly, I'm going to put a wipe button setting in tomorrow morning so that will sort that. Cheers for the report back!

**Comment by NotExpectedYet** [comment]
> On/Off commands working properly now. Status not, but that might be down to that JSON object returned from enclosure plugin.

I've got -dev10 I'm about to comit with the reset button to clear out power settings. Sorry about that, can't wait to get the new UI sorted.
